before:
  hooks:
    - go mod tidy

builds:
  - id: cloudbit
    main: ./cmd/cloudbit
    binary: cloudbit
    ldflags:
      - '-X main.Version={{.Version}}'
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

universal_binaries:
  - id: cloudbit
    replace: false
    name_template: cloudbit

archives:
  - id: cloudbit
    builds:
      - cloudbit
    name_template: cloudbit-{{.Version}}-{{.Os}}-{{.Arch}}
    replacements:
      all: universal
      386: i386
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: cloudbit-ch
    name: cli
  draft: true

snapshot:
  name_template: "{{ incpatch .Version }}-dev"
