name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    strategy:
      matrix:
        go-version: [1.13.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
        artifact: [flow-linux, flow-darwin, flow-windows]

    name: Build
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: go test -v ./...

      - name: Build
        run: go build -v ./...

      - name: Upload built artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.artifact }}
          path: flow
